import { StyleSheet } from 'react-native';
import {
    COLORS,
    FONTS,
    FONT_SIZES,
    SPACING,
    RADIUS,
} from '../../constants/constants';

const styles = StyleSheet.create({
    blur: {
        ...StyleSheet.absoluteFillObject,
    },
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.28)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    outside: {
        ...StyleSheet.absoluteFillObject,
    },
    keyboard: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    card: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: COLORS.background,
        borderRadius: RADIUS.large,
        paddingHorizontal: 24,
        paddingTop: 28,
        paddingBottom: 24,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    closeButton: {
        position: 'absolute',
        right: 16,
        top: 14,
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 5,
    },
    closeText: {
        fontFamily: FONTS.regular,
        fontSize: 27,
        lineHeight: 30,
        fontWeight: '300',
        color: COLORS.textSecondary,
        includeFontPadding: false,
    },
    iconContainer: {
        width: 42,
        height: 42,
        borderRadius: RADIUS.round,
        borderWidth: 1,
        borderColor: COLORS.borderStrong,
        backgroundColor: COLORS.surface,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginBottom: 18,
    },
    icon: {
        fontFamily: FONTS.semiBold,
        fontSize: 18,
        lineHeight: 20,
        color: COLORS.primary,
        includeFontPadding: false,
    },
    title: {
        fontFamily: FONTS.semiBold,
        fontSize: 20,
        lineHeight: 25,
        fontWeight: '600',
        color: COLORS.primary,
        textAlign: 'center',
        includeFontPadding: false,
    },
    subtitle: {
        fontFamily: FONTS.regular,
        fontSize: FONT_SIZES.small,
        lineHeight: 20,
        color: COLORS.primary,
        textAlign: 'center',
        marginTop: 8,
        includeFontPadding: false,
    },
    phone: {
        fontFamily: FONTS.semiBold,
        fontSize: FONT_SIZES.small,
        lineHeight: 20,
        color: COLORS.primary,
        textAlign: 'center',
        marginTop: 2,
        includeFontPadding: false,
    },
    otpWrapper: {
        position: 'relative',
        width: '100%',
        marginTop: 24,
    },
    otpBoxes: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    otpBox: {
        width: 44,
        height: 52,
        borderWidth: 1,
        borderColor: COLORS.border,
        borderRadius: RADIUS.small,
        backgroundColor: COLORS.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    otpBoxActive: {
        borderColor: COLORS.primary,
        borderWidth: 1.5,
    },
    otpBoxError: {
        borderColor: COLORS.primary,
    },
    otpDigit: {
        fontFamily: FONTS.semiBold,
        fontSize: 22,
        lineHeight: 26,
        fontWeight: '600',
        color: COLORS.primary,
        includeFontPadding: false,
    },
    hiddenInput: {
        position: 'absolute',
        left: 0,
        top: 0,
        width: '100%',
        height: '100%',
        opacity: 0,
        color: 'transparent',
    },
    error: {
        fontFamily: FONTS.regular,
        fontSize: FONT_SIZES.small,
        lineHeight: 18,
        color: COLORS.primary,
        textAlign: 'center',
        marginTop: 10,
        includeFontPadding: false,
    },
    verifyButton: {
        width: '100%',
        height: 50,
        marginTop: 20,
        borderRadius: RADIUS.medium,
        padding: 0,
    },

    verifyButtonContent: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },

    buttonText: {
        fontFamily: FONTS.semiBold,
        fontSize: FONT_SIZES.medium,
        lineHeight: 20,
        fontWeight: '600',
        color: COLORS.background,
        textAlign: 'center',
        includeFontPadding: false,
    },
    resendContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 18,
    },
    resendText: {
        fontFamily: FONTS.regular,
        fontSize: FONT_SIZES.small,
        lineHeight: 19,
        color: COLORS.primary,
        includeFontPadding: false,
    },
    resendLink: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZES.medium,
        lineHeight: FONT_SIZES.small,
        fontWeight: '600',
        color: COLORS.themeColor,
        marginLeft: 5,
        includeFontPadding: false,
    },
});

export default styles;